version: '3.9'
services:
  adb-tools:
    build: .
    privileged: true
    volumes:
      - ./data:/data
      - /dev:/dev
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t

